version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: dev.Dockerfile
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    # networks:
    #   - my_network
    # depends_on:
    #   - database

  # Add more containers below (nginx, postgres, etc.)
  # database:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - ./database:/var/lib/postgresql/data/
  #   restart: always
  #   ports:
  #     - 5432:5432
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   my_network:
#     external: true
